### ISSUE TITLE
Database exception when importing zip of documents

### ISSUE THREAD

**Issue by klasocki** [CLARIN-PL/Inforex#77]
The following error occurred when I tried to import a set of files into Inforex (txt+ini).
( each file had a "date = 1970-01-01" line )

```
MDB2 Error: unknown error _doQuery: [Error message: Could not execute statement] [Last executed query: EXECUTE MDB2_STATEMENT_mysql_1c2eec9d32031f67213be0c580c7ceb6 USING @0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10] [Native code: 1292] [Native message: Incorrect date value: '' for column 'date' at row 1]

exception 'DatabaseException' with message 'MDB2 Error: unknown error
_doQuery: [Error message: Could not execute statement]
[Last executed query: EXECUTE MDB2_STATEMENT_mysql_1c2eec9d32031f67213be0c580c7ceb6 USING @0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10]
[Native code: 1292]
[Native message: Incorrect date value: '' for column 'date' at row 1]
' in /home/inforex/engine/include/database/Database.php:116
Stack trace:
#0 /home/inforex/engine/include/database/Database.php(229): Database->execute('INSERT INTO rep...', Array)
#1 /home/inforex/engine/actions/a_upload.php(151): Database->insert('reports', Array)
#2 /home/inforex/engine/include/CInforexWeb.php(105): Action_upload->execute()
#3 /home/inforex/engine/include/CInforexWeb.php(256): InforexWeb->doAction('upload', Array)
#4 /home/inforex/public_html/index.php(89): InforexWeb->execute()
#5 {main}
```

**Comment by mczuk** [comment]
I am sorry for the late response.

The issue has been fixed. Also keep in mind, that the field name in ini file should be "publish_date", not "date". It should be `publish_date = 1970-01-01`

**Comment by klasocki** [comment]
Ok, thank you very much :)

**Comment by apohllo** [comment]
@klasocki can you confirm, that the issue is resolved?
